name: 'fileuploadserver'
version: 0.0.1
description: A web server built using the shelf package.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  http_server: 'any'
  rpc: 'any'
