# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import actions_pb2 as actions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='Proto.JSON',
  syntax='proto3',
  serialized_pb=b'\n\x0b\x65vent.proto\x12\nProto.JSON\x1a\ractions.proto\"\xab\x04\n\revent_message\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x37\n\x06\x64\x65vice\x18\x02 \x01(\x0b\x32\'.Proto.JSON.event_message.device_object\x12\x35\n\x05\x65vent\x18\x03 \x01(\x0b\x32&.Proto.JSON.event_message.event_object\x12;\n\x08position\x18\x04 \x01(\x0b\x32).Proto.JSON.event_message.position_object\x12*\n\x07\x61\x63tions\x18\x05 \x03(\x0b\x32\x19.Proto.JSON.action_object\x1a\x1d\n\rdevice_object\x12\x0c\n\x04imei\x18\x01 \x01(\t\x1a\x89\x01\n\x0c\x65vent_object\x12\x0c\n\x04type\x18\x01 \x01(\t\x12>\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x30.Proto.JSON.event_message.event_object.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x82\x01\n\x0fposition_object\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\x12\r\n\x05speed\x18\x04 \x01(\x01\x12\x0e\n\x06\x63ourse\x18\x05 \x01(\x01\x12\x11\n\televation\x18\x06 \x01(\x01\x12\x10\n\x08\x61\x63\x63uracy\x18\x07 \x01(\x01\x42-\n\x1enet.ktc.miles.model.proto.JSONB\tEventJSONH\x01\x62\x06proto3'
  ,
  dependencies=[actions__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EVENT_MESSAGE_DEVICE_OBJECT = _descriptor.Descriptor(
  name='device_object',
  full_name='Proto.JSON.event_message.device_object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imei', full_name='Proto.JSON.event_message.device_object.imei', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=325,
)

_EVENT_MESSAGE_EVENT_OBJECT_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='Proto.JSON.event_message.event_object.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Proto.JSON.event_message.event_object.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Proto.JSON.event_message.event_object.DataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), b'8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=465,
)

_EVENT_MESSAGE_EVENT_OBJECT = _descriptor.Descriptor(
  name='event_object',
  full_name='Proto.JSON.event_message.event_object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Proto.JSON.event_message.event_object.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='Proto.JSON.event_message.event_object.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EVENT_MESSAGE_EVENT_OBJECT_DATAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=465,
)

_EVENT_MESSAGE_POSITION_OBJECT = _descriptor.Descriptor(
  name='position_object',
  full_name='Proto.JSON.event_message.position_object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Proto.JSON.event_message.position_object.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lat', full_name='Proto.JSON.event_message.position_object.lat', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lon', full_name='Proto.JSON.event_message.position_object.lon', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='Proto.JSON.event_message.position_object.speed', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='course', full_name='Proto.JSON.event_message.position_object.course', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='elevation', full_name='Proto.JSON.event_message.position_object.elevation', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='Proto.JSON.event_message.position_object.accuracy', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=598,
)

_EVENT_MESSAGE = _descriptor.Descriptor(
  name='event_message',
  full_name='Proto.JSON.event_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Proto.JSON.event_message.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device', full_name='Proto.JSON.event_message.device', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event', full_name='Proto.JSON.event_message.event', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='Proto.JSON.event_message.position', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actions', full_name='Proto.JSON.event_message.actions', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EVENT_MESSAGE_DEVICE_OBJECT, _EVENT_MESSAGE_EVENT_OBJECT, _EVENT_MESSAGE_POSITION_OBJECT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=598,
)

_EVENT_MESSAGE_DEVICE_OBJECT.containing_type = _EVENT_MESSAGE
_EVENT_MESSAGE_EVENT_OBJECT_DATAENTRY.containing_type = _EVENT_MESSAGE_EVENT_OBJECT
_EVENT_MESSAGE_EVENT_OBJECT.fields_by_name['data'].message_type = _EVENT_MESSAGE_EVENT_OBJECT_DATAENTRY
_EVENT_MESSAGE_EVENT_OBJECT.containing_type = _EVENT_MESSAGE
_EVENT_MESSAGE_POSITION_OBJECT.containing_type = _EVENT_MESSAGE
_EVENT_MESSAGE.fields_by_name['device'].message_type = _EVENT_MESSAGE_DEVICE_OBJECT
_EVENT_MESSAGE.fields_by_name['event'].message_type = _EVENT_MESSAGE_EVENT_OBJECT
_EVENT_MESSAGE.fields_by_name['position'].message_type = _EVENT_MESSAGE_POSITION_OBJECT
_EVENT_MESSAGE.fields_by_name['actions'].message_type = actions__pb2._ACTION_OBJECT
DESCRIPTOR.message_types_by_name['event_message'] = _EVENT_MESSAGE

event_message = _reflection.GeneratedProtocolMessageType('event_message', (_message.Message,), dict(

  device_object = _reflection.GeneratedProtocolMessageType('device_object', (_message.Message,), dict(
    DESCRIPTOR = _EVENT_MESSAGE_DEVICE_OBJECT,
    __module__ = 'event_pb2'
    # @@protoc_insertion_point(class_scope:Proto.JSON.event_message.device_object)
    ))
  ,

  event_object = _reflection.GeneratedProtocolMessageType('event_object', (_message.Message,), dict(

    DataEntry = _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), dict(
      DESCRIPTOR = _EVENT_MESSAGE_EVENT_OBJECT_DATAENTRY,
      __module__ = 'event_pb2'
      # @@protoc_insertion_point(class_scope:Proto.JSON.event_message.event_object.DataEntry)
      ))
    ,
    DESCRIPTOR = _EVENT_MESSAGE_EVENT_OBJECT,
    __module__ = 'event_pb2'
    # @@protoc_insertion_point(class_scope:Proto.JSON.event_message.event_object)
    ))
  ,

  position_object = _reflection.GeneratedProtocolMessageType('position_object', (_message.Message,), dict(
    DESCRIPTOR = _EVENT_MESSAGE_POSITION_OBJECT,
    __module__ = 'event_pb2'
    # @@protoc_insertion_point(class_scope:Proto.JSON.event_message.position_object)
    ))
  ,
  DESCRIPTOR = _EVENT_MESSAGE,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:Proto.JSON.event_message)
  ))
_sym_db.RegisterMessage(event_message)
_sym_db.RegisterMessage(event_message.device_object)
_sym_db.RegisterMessage(event_message.event_object)
_sym_db.RegisterMessage(event_message.event_object.DataEntry)
_sym_db.RegisterMessage(event_message.position_object)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), b'\n\036net.ktc.miles.model.proto.JSONB\tEventJSONH\001')
_EVENT_MESSAGE_EVENT_OBJECT_DATAENTRY.has_options = True
_EVENT_MESSAGE_EVENT_OBJECT_DATAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), b'8\001')
# @@protoc_insertion_point(module_scope)
