# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geo_positions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='geo_positions.proto',
  package='Proto.JSON',
  syntax='proto3',
  serialized_pb=b'\n\x13geo_positions.proto\x12\nProto.JSON\"\xfa\x01\n\rgeo_positions\x12<\n\tpositions\x18\x01 \x03(\x0b\x32).Proto.JSON.geo_positions.position_object\x1a\xaa\x01\n\x0fposition_object\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\x12\r\n\x05speed\x18\x04 \x01(\x01\x12\x0e\n\x06\x63ourse\x18\x05 \x01(\x01\x12\x11\n\televation\x18\x06 \x01(\x01\x12\x10\n\x08\x61\x63\x63uracy\x18\x07 \x01(\x01\x12\x14\n\x0cis_from_mock\x18\x08 \x01(\x08\x12\x10\n\x08provider\x18\t \x01(\tB0\n\x1enet.ktc.miles.model.proto.JSONB\x0cGeoPositionsH\x01\x62\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GEO_POSITIONS_POSITION_OBJECT = _descriptor.Descriptor(
  name='position_object',
  full_name='Proto.JSON.geo_positions.position_object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Proto.JSON.geo_positions.position_object.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lat', full_name='Proto.JSON.geo_positions.position_object.lat', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lon', full_name='Proto.JSON.geo_positions.position_object.lon', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='Proto.JSON.geo_positions.position_object.speed', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='course', full_name='Proto.JSON.geo_positions.position_object.course', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='elevation', full_name='Proto.JSON.geo_positions.position_object.elevation', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='Proto.JSON.geo_positions.position_object.accuracy', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_from_mock', full_name='Proto.JSON.geo_positions.position_object.is_from_mock', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='provider', full_name='Proto.JSON.geo_positions.position_object.provider', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=286,
)

_GEO_POSITIONS = _descriptor.Descriptor(
  name='geo_positions',
  full_name='Proto.JSON.geo_positions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='Proto.JSON.geo_positions.positions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GEO_POSITIONS_POSITION_OBJECT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=286,
)

_GEO_POSITIONS_POSITION_OBJECT.containing_type = _GEO_POSITIONS
_GEO_POSITIONS.fields_by_name['positions'].message_type = _GEO_POSITIONS_POSITION_OBJECT
DESCRIPTOR.message_types_by_name['geo_positions'] = _GEO_POSITIONS

geo_positions = _reflection.GeneratedProtocolMessageType('geo_positions', (_message.Message,), dict(

  position_object = _reflection.GeneratedProtocolMessageType('position_object', (_message.Message,), dict(
    DESCRIPTOR = _GEO_POSITIONS_POSITION_OBJECT,
    __module__ = 'geo_positions_pb2'
    # @@protoc_insertion_point(class_scope:Proto.JSON.geo_positions.position_object)
    ))
  ,
  DESCRIPTOR = _GEO_POSITIONS,
  __module__ = 'geo_positions_pb2'
  # @@protoc_insertion_point(class_scope:Proto.JSON.geo_positions)
  ))
_sym_db.RegisterMessage(geo_positions)
_sym_db.RegisterMessage(geo_positions.position_object)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), b'\n\036net.ktc.miles.model.proto.JSONB\014GeoPositionsH\001')
# @@protoc_insertion_point(module_scope)
